# Generated by Django 6.0.1 on 2026-04-22 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_documentry_category_food_category_news_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentry',
            name='image',
            field=models.ImageField(upload_to='img'),
        ),
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(upload_to='img'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to='img'),
        ),
        migrations.AlterField(
            model_name='story',
            name='image',
            field=models.ImageField(upload_to='img'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='image',
            field=models.ImageField(upload_to='img'),
        ),
    ]
